export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-12 text-gray-800 leading-7">
      <h1 className="text-3xl font-bold mb-4">Terms and Conditions</h1>

      <p className="text-sm text-gray-500 mb-6">Last Updated: February 2026</p>

      <p className="mb-4">
        Welcome to <strong>Swiftcalcfy</strong>. These Terms and Conditions
        govern your use of our website and calculator tools. By accessing or
        using this website, you agree to comply with these terms. If you do not
        agree, please stop using the website immediately.
      </p>

      {/* ---------------------- Acceptance ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">Acceptance of Terms</h2>

      <p className="mb-4">
        By accessing Swiftcalcfy, you confirm that you are at least 13 years old
        and legally capable of entering into this agreement. Your continued use
        of the site indicates acceptance of these terms and any future updates.
      </p>

      {/* ---------------------- Services ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">Our Services</h2>

      <p className="mb-4">
        Swiftcalcfy provides free online calculators and informational tools for
        finance, health, education, construction, and general purposes. All
        tools are provided for convenience and estimation only.
      </p>

      {/* ---------------------- No Professional Advice ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">
        No Professional Advice
      </h2>

      <p className="mb-4">
        Information and results generated by our calculators do not constitute
        financial, legal, tax, medical, or professional advice. You should
        consult qualified professionals before making decisions based on these
        results.
      </p>

      {/* ---------------------- Use of Website ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">Acceptable Use</h2>

      <p className="mb-2">You agree not to:</p>

      <ul className="list-disc pl-6 mb-4 space-y-1">
        <li>Use the website for unlawful purposes</li>
        <li>Attempt to hack, damage, or disrupt the platform</li>
        <li>Copy or scrape large amounts of content automatically</li>
        <li>Interfere with other users’ experience</li>
        <li>Misuse calculators or data for fraudulent activity</li>
      </ul>

      <p className="mb-4">
        We reserve the right to block or restrict access to users who violate
        these rules.
      </p>

      {/* ---------------------- Ads ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">
        Advertising and Third Party Services
      </h2>

      <p className="mb-4">
        This website may display advertisements through third-party networks
        such as Google AdSense. These services may use cookies or tracking
        technologies. We are not responsible for the content or policies of
        third-party advertisers or external websites.
      </p>

      {/* ---------------------- Intellectual Property ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">Intellectual Property</h2>

      <p className="mb-4">
        All content, design, calculators, code, and branding on Swiftcalcfy are
        owned by us and protected by copyright and intellectual property laws.
        You may not copy, modify, distribute, or reproduce any part of the
        website without written permission.
      </p>

      {/* ---------------------- Limitation ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">
        Limitation of Liability
      </h2>

      <p className="mb-4">
        Swiftcalcfy will not be liable for any direct, indirect, incidental, or
        consequential damages resulting from the use or inability to use this
        website, including losses related to financial or personal decisions
        based on calculator results.
      </p>

      {/* ---------------------- Availability ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">Service Availability</h2>

      <p className="mb-4">
        We may update, modify, or discontinue any part of the website at any
        time without notice. We do not guarantee uninterrupted or error-free
        service.
      </p>

      {/* ---------------------- Privacy ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">Privacy</h2>

      <p className="mb-4">
        Your use of this website is also governed by our Privacy Policy. Please
        review it to understand how information is handled.
      </p>

      {/* ---------------------- Changes ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">Changes to Terms</h2>

      <p className="mb-4">
        We may update these Terms and Conditions at any time. Continued use of
        the website after updates means you accept the revised terms.
      </p>

      {/* ---------------------- Governing Law ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">Governing Law</h2>

      <p className="mb-4">
        These Terms shall be governed by and interpreted according to applicable
        laws. Any disputes shall be handled in the appropriate legal
        jurisdiction.
      </p>

      {/* ---------------------- Contact ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">Contact Us</h2>

      <p>
        For any questions about these Terms, contact:
        <br />
         <a
         href="https://mail.google.com/mail/?view=cm&fs=1&to=swiftcalcfy@gmail.com&su=Feedback%20for%20Swiftcalcfy"
  target="_blank"
  rel="noopener noreferrer"
  className="font-medium text-indigo-600 hover:underline"
      >
        swiftcalcfy@gmail.com
      </a>
      </p>
    </main>
  );
}
