export default function DisclaimerPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-12 text-gray-800 leading-7">
      <h1 className="text-3xl font-bold mb-4">Disclaimer</h1>

      <p className="text-sm text-gray-500 mb-6">Last Updated: February 2026</p>

      <p className="mb-4">
        Welcome to <strong>Swiftcalcfy</strong>. By using this website, you
        agree to the terms outlined in this Disclaimer. If you do not agree,
        please do not use our services.
      </p>

      {/* ---------------------- General Info ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">
        General Information Only
      </h2>

      <p className="mb-4">
        All calculators, tools, and content provided on this website are for
        informational and educational purposes only. Results generated by our
        calculators are estimates and should not be considered professional,
        financial, legal, medical, or technical advice.
      </p>

      {/* ---------------------- Accuracy ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">
        Accuracy of Information
      </h2>

      <p className="mb-4">
        We strive to ensure that all calculations and information are accurate.
        However, we make no guarantees regarding completeness, reliability, or
        accuracy. Small differences may occur due to rounding, formulas, or
        assumptions.
      </p>

      <p className="mb-4">
        You should independently verify results before making any financial or
        personal decisions.
      </p>

      {/* ---------------------- Financial ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">Financial Disclaimer</h2>

      <p className="mb-4">
        Finance related calculators such as EMI, loan, tax, investment, SIP, or
        savings tools are only estimates. They do not represent official bank or
        government calculations. Always consult a qualified financial advisor or
        institution before making financial commitments.
      </p>

      {/* ---------------------- Health ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">Health Disclaimer</h2>

      <p className="mb-4">
        Health and fitness calculators such as BMI, calorie, or body metrics are
        informational only and are not medical advice. Always consult a licensed
        healthcare professional for medical guidance.
      </p>

      {/* ---------------------- Liability ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">
        Limitation of Liability
      </h2>

      <p className="mb-4">
        Swiftcalcfy and its owners will not be liable for any loss, damages, or
        decisions made based on the use of this website or its calculators. Use
        the tools at your own risk.
      </p>

      {/* ---------------------- External Links ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">
        Third Party Links and Ads
      </h2>

      <p className="mb-4">
        Our website may display advertisements or links to third-party websites,
        including services such as Google AdSense. We do not control or endorse
        the content, services, or policies of these external sites and are not
        responsible for their actions.
      </p>

      {/* ---------------------- No Warranty ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">No Warranty</h2>

      <p className="mb-4">
        This website is provided on an "as is" and "as available" basis without
        warranties of any kind, either express or implied.
      </p>

      {/* ---------------------- Consent ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">Your Consent</h2>

      <p className="mb-4">
        By using Swiftcalcfy, you acknowledge that you have read, understood,
        and agreed to this Disclaimer.
      </p>

      {/* ---------------------- Updates ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">Updates</h2>

      <p className="mb-4">
        We may update this Disclaimer at any time. Changes will be posted on
        this page with an updated revision date.
      </p>

      {/* ---------------------- Contact ---------------------- */}

      <h2 className="text-xl font-semibold mt-8 mb-2">Contact Us</h2>

      <p>
        For questions regarding this Disclaimer, contact:
        <br />
        {/* <span className="font-medium">swiftcalcfy@gmail.com</span> */}
         <a
         href="https://mail.google.com/mail/?view=cm&fs=1&to=swiftcalcfy@gmail.com&su=Feedback%20for%20Swiftcalcfy"
  target="_blank"
  rel="noopener noreferrer"
  className="font-medium text-indigo-600 hover:underline"
      >
        swiftcalcfy@gmail.com
      </a>
      </p>
    </main>
  );
}
